### ISSUE TITLE
fab setup_aws script can't handle pre-existing ssh key

### ISSUE THREAD

**Issue by rogueleaderr** [rogueleaderr/definitive_guide_to_django_deployment#18]
If you put in a key name and follow the cp <YOUR PATH TO KEY> command (which actually just creates a file named "ssh" instead of a directory) then later running the fab setup_aws script command will faill with error 

Traceback (most recent call last):
  File "/project/env/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/project/env/local/lib/python2.7/site-packages/fabric/tasks.py", line 405, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/project/env/local/lib/python2.7/site-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
  File "/project/django_deployment/fabfile.py", line 50, in setup_aws_account
    prep_paths(env.ssh_directory, env.deploy_directory)
  File "/project/django_deployment/fabfile.py", line 253, in prep_paths
    os.makedirs(ssh_directory)
  File "/project/env/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/project/django_deployment/deploy/ssh'

**Comment by daljeetv** [comment]
I get the same error with: fab create_instance:webserver
